### ISSUE TITLE
OIDC error when upgrading to SPIRE 1.2.0

### ISSUE THREAD

**Issue by mrsabath** [IBM/trusted-service-identity#126]
When upgrading to Version SPIRE 1.2.0, running a SPIRE
```
  - args:
    - -config
    - /run/spire/oidc/config/oidc-discovery-provider.conf
    image: gcr.io/spiffe-io/oidc-discovery-provider:1.2.0
    imagePullPolicy: IfNotPresent
    name: spire-oidc
```
we get error:
```
trusted-service-identity$k logs spire-server-0 -c spire-oidc
at least one domain must be configured
	main.ParseConfig:139
	main.LoadConfig:125
	main.run:30
	main.main:23
	runtime.main:255
```
