### ISSUE TITLE
Disable modification of webhook created annotations

### ISSUE THREAD

**Issue by mrsabath** [IBM/trusted-service-identity#15]
Once created, the annotation should not be updated by external configuration updates. 

```
annotations:
    admission.trusted.identity/inject: "true"
    admission.trusted.identity/status: injected
    admission.trusted.identity/ti-cluster-name: ti-test1
    admission.trusted.identity/ti-cluster-region: eu-de
    admission.trusted.identity/ti-images: ubuntu:18.04@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
    admission.trusted.identity/ti-secret-key: ti-secret-274e1101-55be-0374-ae4b-5fc47cb34368
```
