### ISSUE TITLE
To prevent CMD modification, add it to workload identity (claims)

### ISSUE THREAD

**Issue by mrsabath** [IBM/trusted-service-identity#64]
We make sure the pod identity contains image(s) for all the containers and initContainers, sha256 encoded, however, we don't protect the identity based on the provided commands. Users might add/modify the CMD values without affecting the identity. 

We should add also the encoded value that contains the following info for all the containers in the pod:

```yaml
image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
command: [ "/bin/bash", "-c", "--" ]
args: [ "while true; do ls /tsi-secrets; sleep 5; done;" ]
```
